name: Build and Deploy in branch

on:
  push:
    branches:
      - dev-2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm i

    - name: Build
      run: npm run build

    - name: Deploy to deploy branch
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git fetch origin
        git checkout -b deploy
        find . -not -path './.git*' -not -path './.github*' -not -name '.' -not -name '..' -delete
        mv build/* .
        rm -rf build
        git add .
        git commit -m "Deploy build to deploy branch"
        git push --force origin deploy
